const mockup = {
  category: [
    {
      id: 73181,
      name: "quang",
      subject: [
        { id: 73184, name: "Test Center" },
        { id: 74788, name: "swdsds" },
        { id: 77414, name: "xsddc" },
        { id: 77415, name: "quang" },
      ],
    },
    {
      id: 73180,
      name: "IT",
      subject: [{ id: 73192, name: "tester" }],
    },
    { id: 73179, name: "Marketing", subject: [] },
    { id: 73178, name: "Kinh doanh", subject: [] },
  ],
  list: [
    {
      id: 1,
      name: "exam",
      description: "description exam",
      language: "vi",
      total_question: 13,
      total_examination_room: 1,
      total_score: 190,
      group_question_id: 73184,
      group_question_name: "Center scscsc",
      created_at: "18/11/2022",
      updated_at: "18/11/2022",
      examination_room: [
        {
          id: 30462,
          name: "xsxs",
          note: null,
          status: 1,
          link_room_exam: "https://cEZ7VHsOJFAOM1RcRyYED0F4SHIX",
          has_time_unlimited: true,
          time_unlimited_str: "Vô thời hạn",
          start_at: null,
          end_at: null,
        },
      ],
    },
    {
      id: 1,
      name: "exam",
      description: "description exam",
      language: "vi",
      total_question: 13,
      total_examination_room: 1,
      total_score: 190,
      group_question_id: 73184,
      group_question_name: "Center scscsc",
      created_at: "18/11/2022",
      updated_at: "18/11/2022",
      examination_room: [
        {
          id: 30462,
          name: "xsxs",
          note: null,
          status: 1,
          link_room_exam: "https://cEZ7VHsOJFAOM1RcRyYED0F4SHIX",
          has_time_unlimited: true,
          time_unlimited_str: "Vô thời hạn",
          start_at: null,
          end_at: null,
        },
      ],
    },
    {
      id: 1,
      name: "exam",
      description: "description exam",
      language: "vi",
      total_question: 13,
      total_examination_room: 1,
      total_score: 190,
      group_question_id: 73184,
      group_question_name: "Center scscsc",
      created_at: "18/11/2022",
      updated_at: "18/11/2022",
      examination_room: [
        {
          id: 30462,
          name: "xsxs",
          note: null,
          status: 1,
          link_room_exam: "https://cEZ7VHsOJFAOM1RcRyYED0F4SHIX",
          has_time_unlimited: true,
          time_unlimited_str: "Vô thời hạn",
          start_at: null,
          end_at: null,
        },
      ],
    },
  ],
  pagination: {
    total_items: 5,
    total_pages: 5,
    current_page: 1,
    rows: 10,
  },
};

export default mockup;
